USE MoviesDatabase
:On Error exit
--CREATES MOVIES DATABASE
PRINT 'CREATING DATABASE'
:r Install\Test.sql
--CREATES TABLES
PRINT 'CREATING TABLES'
:r Install\Test.sql
--INSERTS DATA IN TABLES
PRINT 'INSERTING DATA'
:r Install\Test.sql
--SETS INNER JOINS
PRINT 'SETTING INNER JOINS'
:r Install\Test.sql
--CREATES INSERTION PROCEDURE
PRINT 'CREATING INSERTION PROCEDURE'
:r Install\Test.sql